CREATE TABLE comments (
  id SERIAL PRIMARY KEY,
  content TEXT NOT NULL,
  userId INTEGER REFERENCES users(id) ON DELETE CASCADE,
  postId INTEGER REFERENCES posts(id) ON DELETE CASCADE,
  createdAt TIMESTAMPTZ DEFAULT NOW()
);